server:
    port: 8088

# spring:
#     # oracle DB
#     datasource:
#         driver-class-name: oracle.jdbc.driver.OracleDriver
#         url: jdbc:oracle:thin:@localhost:1521/xe
#         username: hr
#         password: hr

#     # jpa
#     jpa:
#         properties:
#             hibernate:
#                 dialect: org.hibernate.dialect.OracleDialect
#                 show_sql: true
#                 format_sql: true
#                 use_sql_comments: true
#         hibernate :
#             ddl-auto: none

spring:
    # h2
    # db 설정은 여기에서 바꾸면 됨
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:testdb
        username: sa
        password: 
    h2:
        console:
            enabled: true 
    # jpa
    jpa:
        hibernate :
            ddl-auto: update
        show-sql: true


# token
jwt:
    secret: ${JWT_SECRET_KEY}


# yml은 들여 쓰기